services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_STUDENT_TAG_ID: ${REACT_APP_STUDENT_TAG_ID}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${CLIENT_PORT}:3000'

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:3000'

